/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.testfordatabase.swagger.api;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;

import javax.validation.constraints.*;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-03-19T14:53:52.454350+01:00[Europe/Berlin]")
@Validated
@Api(value = "tags", description = "the tags API")
public interface TagsApi {

    default TagsApiDelegate getDelegate() {
        return new TagsApiDelegate() {};
    }

    /**
     * GET /tags : Get tags
     * Get tags. Auth not required
     *
     * @return OK (status code 200)
     *         or Unexpected error (status code 422)
     */
    @ApiOperation(value = "Get tags", nickname = "tagsGet", notes = "Get tags. Auth not required", response = TagsResponseData.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = TagsResponseData.class),
        @ApiResponse(code = 422, message = "Unexpected error", response = GenericErrorModelData.class) })
    @GetMapping(
        value = "/tags",
        produces = { "application/json" }
    )
    default ResponseEntity<TagsResponseData> tagsGet() {
        return getDelegate().tagsGet();
    }

}
