###
# CREATE USER
< {%
    request.variables.set("auth_token", "")
%}
POST {{base-url}}/createuser  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "user": {
    "username": "huk",
    "email": "huk@mail.ru?",
    "password": "You have to believe. Please"
  }
}


###
# LOGIN
POST {{base-url}}/login  HTTP/1.1
Content-Type: application/json

{
  "user": {
    "email": "huk@mail.ru?",
    "password": "You have to believe. Please"
  }
}

###
# LOGIN
GET {{base-url}}/getcurrentuser  HTTP/1.1
Content-Type: application/json